name: Run Test Manually

on:
  workflow_dispatch:
    inputs:
      TAG:
        description: "Type which test tag you want to run"
        required: false
        default: "@regression"

permissions: write-all

jobs:
  test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          npm i

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          xvfb-run --auto-servernum npm run tag ${{ inputs.TAG }}
        env:
          DISPLAY: ":99"

      - name: Generate allure report
        if: always()
        run: npm run generate-allure

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report
          path: allure-report
          retention-days: 30
